/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AiSeoServicesRouteImport } from './routes/ai-seo-services'
import { Route as AndroidAppDevelopmentServicesRouteImport } from './routes/android-app-development-services'
import { Route as BannerDesignServicesRouteImport } from './routes/banner-design-services'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentWritingServicesRouteImport } from './routes/content-writing-services'
import { Route as CustomCmsWebsiteDesignDevelopmentRouteImport } from './routes/custom-cms-website-design-development'
import { Route as EcommerceSeoServicesRouteImport } from './routes/ecommerce-seo-services'
import { Route as EcommerceWebsiteDevelopementRouteImport } from './routes/ecommerce-website-developement'
import { Route as GraphicDesignServicesRouteImport } from './routes/graphic-design-services'
import { Route as HireAwsDevelopersRouteImport } from './routes/hire-aws-developers'
import { Route as HireFlutterAppDevelopersRouteImport } from './routes/hire-flutter-app-developers'
import { Route as HireJavascriptDevelopersRouteImport } from './routes/hire-javascript-developers'
import { Route as HireLaravelDevelopersRouteImport } from './routes/hire-laravel-developers'
import { Route as HireMagentoDevelopersRouteImport } from './routes/hire-magento-developers'
import { Route as HirePhpDevelopersRouteImport } from './routes/hire-php-developers'
import { Route as HirePythonDevelopersRouteImport } from './routes/hire-python-developers'
import { Route as HireReactNativeAppDeveloperRouteImport } from './routes/hire-react-native-app-developer'
import { Route as HireReactjsDevelopersRouteImport } from './routes/hire-reactjs-developers'
import { Route as HireShopifyDevelopersRouteImport } from './routes/hire-shopify-developers'
import { Route as HireWixDevelopersRouteImport } from './routes/hire-wix-developers'
import { Route as HireWordpressDevelopersRouteImport } from './routes/hire-wordpress-developers'
import { Route as HospitalManagementSoftwareRouteImport } from './routes/hospital-management-software'
import { Route as HrmSoftwareRouteImport } from './routes/hrm-software'
import { Route as ImageEditingRouteImport } from './routes/image-editing'
import { Route as IosAppDevelopmentCompanyRouteImport } from './routes/ios-app-development-company'
import { Route as LandingPageDesignRouteImport } from './routes/landing-page-design'
import { Route as LocalSeoServicesRouteImport } from './routes/local-seo-services'
import { Route as LogoDesignCompanyRouteImport } from './routes/logo-design-company'
import { Route as MobileAppDevelopmentServicesRouteImport } from './routes/mobile-app-development-services'
import { Route as OnlineReputationManagementCompanyRouteImport } from './routes/online-reputation-management-company'
import { Route as OurTermsConditionsRouteImport } from './routes/our-terms-conditions'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as PayrollSoftwareRouteImport } from './routes/payroll-software'
import { Route as PpcServicesCompanyIndiaRouteImport } from './routes/ppc-services-company-india'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SchoolErpSoftwareRouteImport } from './routes/school-erp-software'
import { Route as SeoCompanyInDelhiRouteImport } from './routes/seo-company-in-delhi'
import { Route as SeoCompanyIndiaRouteImport } from './routes/seo-company-india'
import { Route as SeoOutsourcingServicesRouteImport } from './routes/seo-outsourcing-services'
import { Route as SeoServicesIndiaRouteImport } from './routes/seo-services-india'
import { Route as SmoCompanyInIndiaRouteImport } from './routes/smo-company-in-india'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as UiUxWebsiteDesignCompanyRouteImport } from './routes/ui-ux-website-design-company'
import { Route as WebDevelopmentRouteImport } from './routes/web-development'
import { Route as WebsiteDesignCompanyIndiaRouteImport } from './routes/website-design-company-india'
import { Route as WebsiteRedesignCompanyRouteImport } from './routes/website-redesign-company'
import { Route as WindowsAppDevelopmentServicesRouteImport } from './routes/windows-app-development-services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSeoServicesRoute = AiSeoServicesRouteImport.update({
  id: '/ai-seo-services',
  path: '/ai-seo-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidAppDevelopmentServicesRoute =
  AndroidAppDevelopmentServicesRouteImport.update({
    id: '/android-app-development-services',
    path: '/android-app-development-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const BannerDesignServicesRoute = BannerDesignServicesRouteImport.update({
  id: '/banner-design-services',
  path: '/banner-design-services',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentWritingServicesRoute = ContentWritingServicesRouteImport.update({
  id: '/content-writing-services',
  path: '/content-writing-services',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCmsWebsiteDesignDevelopmentRoute =
  CustomCmsWebsiteDesignDevelopmentRouteImport.update({
    id: '/custom-cms-website-design-development',
    path: '/custom-cms-website-design-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const EcommerceSeoServicesRoute = EcommerceSeoServicesRouteImport.update({
  id: '/ecommerce-seo-services',
  path: '/ecommerce-seo-services',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceWebsiteDevelopementRoute =
  EcommerceWebsiteDevelopementRouteImport.update({
    id: '/ecommerce-website-developement',
    path: '/ecommerce-website-developement',
    getParentRoute: () => rootRouteImport,
  } as any)
const GraphicDesignServicesRoute = GraphicDesignServicesRouteImport.update({
  id: '/graphic-design-services',
  path: '/graphic-design-services',
  getParentRoute: () => rootRouteImport,
} as any)
const HireAwsDevelopersRoute = HireAwsDevelopersRouteImport.update({
  id: '/hire-aws-developers',
  path: '/hire-aws-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireFlutterAppDevelopersRoute =
  HireFlutterAppDevelopersRouteImport.update({
    id: '/hire-flutter-app-developers',
    path: '/hire-flutter-app-developers',
    getParentRoute: () => rootRouteImport,
  } as any)
const HireJavascriptDevelopersRoute =
  HireJavascriptDevelopersRouteImport.update({
    id: '/hire-javascript-developers',
    path: '/hire-javascript-developers',
    getParentRoute: () => rootRouteImport,
  } as any)
const HireLaravelDevelopersRoute = HireLaravelDevelopersRouteImport.update({
  id: '/hire-laravel-developers',
  path: '/hire-laravel-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireMagentoDevelopersRoute = HireMagentoDevelopersRouteImport.update({
  id: '/hire-magento-developers',
  path: '/hire-magento-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HirePhpDevelopersRoute = HirePhpDevelopersRouteImport.update({
  id: '/hire-php-developers',
  path: '/hire-php-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HirePythonDevelopersRoute = HirePythonDevelopersRouteImport.update({
  id: '/hire-python-developers',
  path: '/hire-python-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireReactNativeAppDeveloperRoute =
  HireReactNativeAppDeveloperRouteImport.update({
    id: '/hire-react-native-app-developer',
    path: '/hire-react-native-app-developer',
    getParentRoute: () => rootRouteImport,
  } as any)
const HireReactjsDevelopersRoute = HireReactjsDevelopersRouteImport.update({
  id: '/hire-reactjs-developers',
  path: '/hire-reactjs-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireShopifyDevelopersRoute = HireShopifyDevelopersRouteImport.update({
  id: '/hire-shopify-developers',
  path: '/hire-shopify-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireWixDevelopersRoute = HireWixDevelopersRouteImport.update({
  id: '/hire-wix-developers',
  path: '/hire-wix-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireWordpressDevelopersRoute = HireWordpressDevelopersRouteImport.update({
  id: '/hire-wordpress-developers',
  path: '/hire-wordpress-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalManagementSoftwareRoute =
  HospitalManagementSoftwareRouteImport.update({
    id: '/hospital-management-software',
    path: '/hospital-management-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const HrmSoftwareRoute = HrmSoftwareRouteImport.update({
  id: '/hrm-software',
  path: '/hrm-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageEditingRoute = ImageEditingRouteImport.update({
  id: '/image-editing',
  path: '/image-editing',
  getParentRoute: () => rootRouteImport,
} as any)
const IosAppDevelopmentCompanyRoute =
  IosAppDevelopmentCompanyRouteImport.update({
    id: '/ios-app-development-company',
    path: '/ios-app-development-company',
    getParentRoute: () => rootRouteImport,
  } as any)
const LandingPageDesignRoute = LandingPageDesignRouteImport.update({
  id: '/landing-page-design',
  path: '/landing-page-design',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSeoServicesRoute = LocalSeoServicesRouteImport.update({
  id: '/local-seo-services',
  path: '/local-seo-services',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoDesignCompanyRoute = LogoDesignCompanyRouteImport.update({
  id: '/logo-design-company',
  path: '/logo-design-company',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppDevelopmentServicesRoute =
  MobileAppDevelopmentServicesRouteImport.update({
    id: '/mobile-app-development-services',
    path: '/mobile-app-development-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnlineReputationManagementCompanyRoute =
  OnlineReputationManagementCompanyRouteImport.update({
    id: '/online-reputation-management-company',
    path: '/online-reputation-management-company',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurTermsConditionsRoute = OurTermsConditionsRouteImport.update({
  id: '/our-terms-conditions',
  path: '/our-terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollSoftwareRoute = PayrollSoftwareRouteImport.update({
  id: '/payroll-software',
  path: '/payroll-software',
  getParentRoute: () => rootRouteImport,
} as any)
const PpcServicesCompanyIndiaRoute = PpcServicesCompanyIndiaRouteImport.update({
  id: '/ppc-services-company-india',
  path: '/ppc-services-company-india',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolErpSoftwareRoute = SchoolErpSoftwareRouteImport.update({
  id: '/school-erp-software',
  path: '/school-erp-software',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoCompanyInDelhiRoute = SeoCompanyInDelhiRouteImport.update({
  id: '/seo-company-in-delhi',
  path: '/seo-company-in-delhi',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoCompanyIndiaRoute = SeoCompanyIndiaRouteImport.update({
  id: '/seo-company-india',
  path: '/seo-company-india',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoOutsourcingServicesRoute = SeoOutsourcingServicesRouteImport.update({
  id: '/seo-outsourcing-services',
  path: '/seo-outsourcing-services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoServicesIndiaRoute = SeoServicesIndiaRouteImport.update({
  id: '/seo-services-india',
  path: '/seo-services-india',
  getParentRoute: () => rootRouteImport,
} as any)
const SmoCompanyInIndiaRoute = SmoCompanyInIndiaRouteImport.update({
  id: '/smo-company-in-india',
  path: '/smo-company-in-india',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const UiUxWebsiteDesignCompanyRoute =
  UiUxWebsiteDesignCompanyRouteImport.update({
    id: '/ui-ux-website-design-company',
    path: '/ui-ux-website-design-company',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebDevelopmentRoute = WebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteDesignCompanyIndiaRoute =
  WebsiteDesignCompanyIndiaRouteImport.update({
    id: '/website-design-company-india',
    path: '/website-design-company-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteRedesignCompanyRoute = WebsiteRedesignCompanyRouteImport.update({
  id: '/website-redesign-company',
  path: '/website-redesign-company',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowsAppDevelopmentServicesRoute =
  WindowsAppDevelopmentServicesRouteImport.update({
    id: '/windows-app-development-services',
    path: '/windows-app-development-services',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-seo-services': typeof AiSeoServicesRoute
  '/android-app-development-services': typeof AndroidAppDevelopmentServicesRoute
  '/banner-design-services': typeof BannerDesignServicesRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/content-writing-services': typeof ContentWritingServicesRoute
  '/custom-cms-website-design-development': typeof CustomCmsWebsiteDesignDevelopmentRoute
  '/ecommerce-seo-services': typeof EcommerceSeoServicesRoute
  '/ecommerce-website-developement': typeof EcommerceWebsiteDevelopementRoute
  '/graphic-design-services': typeof GraphicDesignServicesRoute
  '/hire-aws-developers': typeof HireAwsDevelopersRoute
  '/hire-flutter-app-developers': typeof HireFlutterAppDevelopersRoute
  '/hire-javascript-developers': typeof HireJavascriptDevelopersRoute
  '/hire-laravel-developers': typeof HireLaravelDevelopersRoute
  '/hire-magento-developers': typeof HireMagentoDevelopersRoute
  '/hire-php-developers': typeof HirePhpDevelopersRoute
  '/hire-python-developers': typeof HirePythonDevelopersRoute
  '/hire-react-native-app-developer': typeof HireReactNativeAppDeveloperRoute
  '/hire-reactjs-developers': typeof HireReactjsDevelopersRoute
  '/hire-shopify-developers': typeof HireShopifyDevelopersRoute
  '/hire-wix-developers': typeof HireWixDevelopersRoute
  '/hire-wordpress-developers': typeof HireWordpressDevelopersRoute
  '/hospital-management-software': typeof HospitalManagementSoftwareRoute
  '/hrm-software': typeof HrmSoftwareRoute
  '/image-editing': typeof ImageEditingRoute
  '/ios-app-development-company': typeof IosAppDevelopmentCompanyRoute
  '/landing-page-design': typeof LandingPageDesignRoute
  '/local-seo-services': typeof LocalSeoServicesRoute
  '/logo-design-company': typeof LogoDesignCompanyRoute
  '/mobile-app-development-services': typeof MobileAppDevelopmentServicesRoute
  '/online-reputation-management-company': typeof OnlineReputationManagementCompanyRoute
  '/our-terms-conditions': typeof OurTermsConditionsRoute
  '/our-work': typeof OurWorkRoute
  '/payroll-software': typeof PayrollSoftwareRoute
  '/ppc-services-company-india': typeof PpcServicesCompanyIndiaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/school-erp-software': typeof SchoolErpSoftwareRoute
  '/seo-company-in-delhi': typeof SeoCompanyInDelhiRoute
  '/seo-company-india': typeof SeoCompanyIndiaRoute
  '/seo-outsourcing-services': typeof SeoOutsourcingServicesRoute
  '/seo-services-india': typeof SeoServicesIndiaRoute
  '/smo-company-in-india': typeof SmoCompanyInIndiaRoute
  '/testimonials': typeof TestimonialsRoute
  '/ui-ux-website-design-company': typeof UiUxWebsiteDesignCompanyRoute
  '/web-development': typeof WebDevelopmentRoute
  '/website-design-company-india': typeof WebsiteDesignCompanyIndiaRoute
  '/website-redesign-company': typeof WebsiteRedesignCompanyRoute
  '/windows-app-development-services': typeof WindowsAppDevelopmentServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-seo-services': typeof AiSeoServicesRoute
  '/android-app-development-services': typeof AndroidAppDevelopmentServicesRoute
  '/banner-design-services': typeof BannerDesignServicesRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/content-writing-services': typeof ContentWritingServicesRoute
  '/custom-cms-website-design-development': typeof CustomCmsWebsiteDesignDevelopmentRoute
  '/ecommerce-seo-services': typeof EcommerceSeoServicesRoute
  '/ecommerce-website-developement': typeof EcommerceWebsiteDevelopementRoute
  '/graphic-design-services': typeof GraphicDesignServicesRoute
  '/hire-aws-developers': typeof HireAwsDevelopersRoute
  '/hire-flutter-app-developers': typeof HireFlutterAppDevelopersRoute
  '/hire-javascript-developers': typeof HireJavascriptDevelopersRoute
  '/hire-laravel-developers': typeof HireLaravelDevelopersRoute
  '/hire-magento-developers': typeof HireMagentoDevelopersRoute
  '/hire-php-developers': typeof HirePhpDevelopersRoute
  '/hire-python-developers': typeof HirePythonDevelopersRoute
  '/hire-react-native-app-developer': typeof HireReactNativeAppDeveloperRoute
  '/hire-reactjs-developers': typeof HireReactjsDevelopersRoute
  '/hire-shopify-developers': typeof HireShopifyDevelopersRoute
  '/hire-wix-developers': typeof HireWixDevelopersRoute
  '/hire-wordpress-developers': typeof HireWordpressDevelopersRoute
  '/hospital-management-software': typeof HospitalManagementSoftwareRoute
  '/hrm-software': typeof HrmSoftwareRoute
  '/image-editing': typeof ImageEditingRoute
  '/ios-app-development-company': typeof IosAppDevelopmentCompanyRoute
  '/landing-page-design': typeof LandingPageDesignRoute
  '/local-seo-services': typeof LocalSeoServicesRoute
  '/logo-design-company': typeof LogoDesignCompanyRoute
  '/mobile-app-development-services': typeof MobileAppDevelopmentServicesRoute
  '/online-reputation-management-company': typeof OnlineReputationManagementCompanyRoute
  '/our-terms-conditions': typeof OurTermsConditionsRoute
  '/our-work': typeof OurWorkRoute
  '/payroll-software': typeof PayrollSoftwareRoute
  '/ppc-services-company-india': typeof PpcServicesCompanyIndiaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/school-erp-software': typeof SchoolErpSoftwareRoute
  '/seo-company-in-delhi': typeof SeoCompanyInDelhiRoute
  '/seo-company-india': typeof SeoCompanyIndiaRoute
  '/seo-outsourcing-services': typeof SeoOutsourcingServicesRoute
  '/seo-services-india': typeof SeoServicesIndiaRoute
  '/smo-company-in-india': typeof SmoCompanyInIndiaRoute
  '/testimonials': typeof TestimonialsRoute
  '/ui-ux-website-design-company': typeof UiUxWebsiteDesignCompanyRoute
  '/web-development': typeof WebDevelopmentRoute
  '/website-design-company-india': typeof WebsiteDesignCompanyIndiaRoute
  '/website-redesign-company': typeof WebsiteRedesignCompanyRoute
  '/windows-app-development-services': typeof WindowsAppDevelopmentServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-seo-services': typeof AiSeoServicesRoute
  '/android-app-development-services': typeof AndroidAppDevelopmentServicesRoute
  '/banner-design-services': typeof BannerDesignServicesRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/content-writing-services': typeof ContentWritingServicesRoute
  '/custom-cms-website-design-development': typeof CustomCmsWebsiteDesignDevelopmentRoute
  '/ecommerce-seo-services': typeof EcommerceSeoServicesRoute
  '/ecommerce-website-developement': typeof EcommerceWebsiteDevelopementRoute
  '/graphic-design-services': typeof GraphicDesignServicesRoute
  '/hire-aws-developers': typeof HireAwsDevelopersRoute
  '/hire-flutter-app-developers': typeof HireFlutterAppDevelopersRoute
  '/hire-javascript-developers': typeof HireJavascriptDevelopersRoute
  '/hire-laravel-developers': typeof HireLaravelDevelopersRoute
  '/hire-magento-developers': typeof HireMagentoDevelopersRoute
  '/hire-php-developers': typeof HirePhpDevelopersRoute
  '/hire-python-developers': typeof HirePythonDevelopersRoute
  '/hire-react-native-app-developer': typeof HireReactNativeAppDeveloperRoute
  '/hire-reactjs-developers': typeof HireReactjsDevelopersRoute
  '/hire-shopify-developers': typeof HireShopifyDevelopersRoute
  '/hire-wix-developers': typeof HireWixDevelopersRoute
  '/hire-wordpress-developers': typeof HireWordpressDevelopersRoute
  '/hospital-management-software': typeof HospitalManagementSoftwareRoute
  '/hrm-software': typeof HrmSoftwareRoute
  '/image-editing': typeof ImageEditingRoute
  '/ios-app-development-company': typeof IosAppDevelopmentCompanyRoute
  '/landing-page-design': typeof LandingPageDesignRoute
  '/local-seo-services': typeof LocalSeoServicesRoute
  '/logo-design-company': typeof LogoDesignCompanyRoute
  '/mobile-app-development-services': typeof MobileAppDevelopmentServicesRoute
  '/online-reputation-management-company': typeof OnlineReputationManagementCompanyRoute
  '/our-terms-conditions': typeof OurTermsConditionsRoute
  '/our-work': typeof OurWorkRoute
  '/payroll-software': typeof PayrollSoftwareRoute
  '/ppc-services-company-india': typeof PpcServicesCompanyIndiaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/school-erp-software': typeof SchoolErpSoftwareRoute
  '/seo-company-in-delhi': typeof SeoCompanyInDelhiRoute
  '/seo-company-india': typeof SeoCompanyIndiaRoute
  '/seo-outsourcing-services': typeof SeoOutsourcingServicesRoute
  '/seo-services-india': typeof SeoServicesIndiaRoute
  '/smo-company-in-india': typeof SmoCompanyInIndiaRoute
  '/testimonials': typeof TestimonialsRoute
  '/ui-ux-website-design-company': typeof UiUxWebsiteDesignCompanyRoute
  '/web-development': typeof WebDevelopmentRoute
  '/website-design-company-india': typeof WebsiteDesignCompanyIndiaRoute
  '/website-redesign-company': typeof WebsiteRedesignCompanyRoute
  '/windows-app-development-services': typeof WindowsAppDevelopmentServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/ai-seo-services'
    | '/android-app-development-services'
    | '/banner-design-services'
    | '/career'
    | '/contact'
    | '/content-writing-services'
    | '/custom-cms-website-design-development'
    | '/ecommerce-seo-services'
    | '/ecommerce-website-developement'
    | '/graphic-design-services'
    | '/hire-aws-developers'
    | '/hire-flutter-app-developers'
    | '/hire-javascript-developers'
    | '/hire-laravel-developers'
    | '/hire-magento-developers'
    | '/hire-php-developers'
    | '/hire-python-developers'
    | '/hire-react-native-app-developer'
    | '/hire-reactjs-developers'
    | '/hire-shopify-developers'
    | '/hire-wix-developers'
    | '/hire-wordpress-developers'
    | '/hospital-management-software'
    | '/hrm-software'
    | '/image-editing'
    | '/ios-app-development-company'
    | '/landing-page-design'
    | '/local-seo-services'
    | '/logo-design-company'
    | '/mobile-app-development-services'
    | '/online-reputation-management-company'
    | '/our-terms-conditions'
    | '/our-work'
    | '/payroll-software'
    | '/ppc-services-company-india'
    | '/privacy-policy'
    | '/school-erp-software'
    | '/seo-company-in-delhi'
    | '/seo-company-india'
    | '/seo-outsourcing-services'
    | '/seo-services-india'
    | '/smo-company-in-india'
    | '/testimonials'
    | '/ui-ux-website-design-company'
    | '/web-development'
    | '/website-design-company-india'
    | '/website-redesign-company'
    | '/windows-app-development-services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/ai-seo-services'
    | '/android-app-development-services'
    | '/banner-design-services'
    | '/career'
    | '/contact'
    | '/content-writing-services'
    | '/custom-cms-website-design-development'
    | '/ecommerce-seo-services'
    | '/ecommerce-website-developement'
    | '/graphic-design-services'
    | '/hire-aws-developers'
    | '/hire-flutter-app-developers'
    | '/hire-javascript-developers'
    | '/hire-laravel-developers'
    | '/hire-magento-developers'
    | '/hire-php-developers'
    | '/hire-python-developers'
    | '/hire-react-native-app-developer'
    | '/hire-reactjs-developers'
    | '/hire-shopify-developers'
    | '/hire-wix-developers'
    | '/hire-wordpress-developers'
    | '/hospital-management-software'
    | '/hrm-software'
    | '/image-editing'
    | '/ios-app-development-company'
    | '/landing-page-design'
    | '/local-seo-services'
    | '/logo-design-company'
    | '/mobile-app-development-services'
    | '/online-reputation-management-company'
    | '/our-terms-conditions'
    | '/our-work'
    | '/payroll-software'
    | '/ppc-services-company-india'
    | '/privacy-policy'
    | '/school-erp-software'
    | '/seo-company-in-delhi'
    | '/seo-company-india'
    | '/seo-outsourcing-services'
    | '/seo-services-india'
    | '/smo-company-in-india'
    | '/testimonials'
    | '/ui-ux-website-design-company'
    | '/web-development'
    | '/website-design-company-india'
    | '/website-redesign-company'
    | '/windows-app-development-services'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/ai-seo-services'
    | '/android-app-development-services'
    | '/banner-design-services'
    | '/career'
    | '/contact'
    | '/content-writing-services'
    | '/custom-cms-website-design-development'
    | '/ecommerce-seo-services'
    | '/ecommerce-website-developement'
    | '/graphic-design-services'
    | '/hire-aws-developers'
    | '/hire-flutter-app-developers'
    | '/hire-javascript-developers'
    | '/hire-laravel-developers'
    | '/hire-magento-developers'
    | '/hire-php-developers'
    | '/hire-python-developers'
    | '/hire-react-native-app-developer'
    | '/hire-reactjs-developers'
    | '/hire-shopify-developers'
    | '/hire-wix-developers'
    | '/hire-wordpress-developers'
    | '/hospital-management-software'
    | '/hrm-software'
    | '/image-editing'
    | '/ios-app-development-company'
    | '/landing-page-design'
    | '/local-seo-services'
    | '/logo-design-company'
    | '/mobile-app-development-services'
    | '/online-reputation-management-company'
    | '/our-terms-conditions'
    | '/our-work'
    | '/payroll-software'
    | '/ppc-services-company-india'
    | '/privacy-policy'
    | '/school-erp-software'
    | '/seo-company-in-delhi'
    | '/seo-company-india'
    | '/seo-outsourcing-services'
    | '/seo-services-india'
    | '/smo-company-in-india'
    | '/testimonials'
    | '/ui-ux-website-design-company'
    | '/web-development'
    | '/website-design-company-india'
    | '/website-redesign-company'
    | '/windows-app-development-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AiSeoServicesRoute: typeof AiSeoServicesRoute
  AndroidAppDevelopmentServicesRoute: typeof AndroidAppDevelopmentServicesRoute
  BannerDesignServicesRoute: typeof BannerDesignServicesRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  ContentWritingServicesRoute: typeof ContentWritingServicesRoute
  CustomCmsWebsiteDesignDevelopmentRoute: typeof CustomCmsWebsiteDesignDevelopmentRoute
  EcommerceSeoServicesRoute: typeof EcommerceSeoServicesRoute
  EcommerceWebsiteDevelopementRoute: typeof EcommerceWebsiteDevelopementRoute
  GraphicDesignServicesRoute: typeof GraphicDesignServicesRoute
  HireAwsDevelopersRoute: typeof HireAwsDevelopersRoute
  HireFlutterAppDevelopersRoute: typeof HireFlutterAppDevelopersRoute
  HireJavascriptDevelopersRoute: typeof HireJavascriptDevelopersRoute
  HireLaravelDevelopersRoute: typeof HireLaravelDevelopersRoute
  HireMagentoDevelopersRoute: typeof HireMagentoDevelopersRoute
  HirePhpDevelopersRoute: typeof HirePhpDevelopersRoute
  HirePythonDevelopersRoute: typeof HirePythonDevelopersRoute
  HireReactNativeAppDeveloperRoute: typeof HireReactNativeAppDeveloperRoute
  HireReactjsDevelopersRoute: typeof HireReactjsDevelopersRoute
  HireShopifyDevelopersRoute: typeof HireShopifyDevelopersRoute
  HireWixDevelopersRoute: typeof HireWixDevelopersRoute
  HireWordpressDevelopersRoute: typeof HireWordpressDevelopersRoute
  HospitalManagementSoftwareRoute: typeof HospitalManagementSoftwareRoute
  HrmSoftwareRoute: typeof HrmSoftwareRoute
  ImageEditingRoute: typeof ImageEditingRoute
  IosAppDevelopmentCompanyRoute: typeof IosAppDevelopmentCompanyRoute
  LandingPageDesignRoute: typeof LandingPageDesignRoute
  LocalSeoServicesRoute: typeof LocalSeoServicesRoute
  LogoDesignCompanyRoute: typeof LogoDesignCompanyRoute
  MobileAppDevelopmentServicesRoute: typeof MobileAppDevelopmentServicesRoute
  OnlineReputationManagementCompanyRoute: typeof OnlineReputationManagementCompanyRoute
  OurTermsConditionsRoute: typeof OurTermsConditionsRoute
  OurWorkRoute: typeof OurWorkRoute
  PayrollSoftwareRoute: typeof PayrollSoftwareRoute
  PpcServicesCompanyIndiaRoute: typeof PpcServicesCompanyIndiaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SchoolErpSoftwareRoute: typeof SchoolErpSoftwareRoute
  SeoCompanyInDelhiRoute: typeof SeoCompanyInDelhiRoute
  SeoCompanyIndiaRoute: typeof SeoCompanyIndiaRoute
  SeoOutsourcingServicesRoute: typeof SeoOutsourcingServicesRoute
  SeoServicesIndiaRoute: typeof SeoServicesIndiaRoute
  SmoCompanyInIndiaRoute: typeof SmoCompanyInIndiaRoute
  TestimonialsRoute: typeof TestimonialsRoute
  UiUxWebsiteDesignCompanyRoute: typeof UiUxWebsiteDesignCompanyRoute
  WebDevelopmentRoute: typeof WebDevelopmentRoute
  WebsiteDesignCompanyIndiaRoute: typeof WebsiteDesignCompanyIndiaRoute
  WebsiteRedesignCompanyRoute: typeof WebsiteRedesignCompanyRoute
  WindowsAppDevelopmentServicesRoute: typeof WindowsAppDevelopmentServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo-services': {
      id: '/ai-seo-services'
      path: '/ai-seo-services'
      fullPath: '/ai-seo-services'
      preLoaderRoute: typeof AiSeoServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android-app-development-services': {
      id: '/android-app-development-services'
      path: '/android-app-development-services'
      fullPath: '/android-app-development-services'
      preLoaderRoute: typeof AndroidAppDevelopmentServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banner-design-services': {
      id: '/banner-design-services'
      path: '/banner-design-services'
      fullPath: '/banner-design-services'
      preLoaderRoute: typeof BannerDesignServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-writing-services': {
      id: '/content-writing-services'
      path: '/content-writing-services'
      fullPath: '/content-writing-services'
      preLoaderRoute: typeof ContentWritingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-cms-website-design-development': {
      id: '/custom-cms-website-design-development'
      path: '/custom-cms-website-design-development'
      fullPath: '/custom-cms-website-design-development'
      preLoaderRoute: typeof CustomCmsWebsiteDesignDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce-seo-services': {
      id: '/ecommerce-seo-services'
      path: '/ecommerce-seo-services'
      fullPath: '/ecommerce-seo-services'
      preLoaderRoute: typeof EcommerceSeoServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce-website-developement': {
      id: '/ecommerce-website-developement'
      path: '/ecommerce-website-developement'
      fullPath: '/ecommerce-website-developement'
      preLoaderRoute: typeof EcommerceWebsiteDevelopementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphic-design-services': {
      id: '/graphic-design-services'
      path: '/graphic-design-services'
      fullPath: '/graphic-design-services'
      preLoaderRoute: typeof GraphicDesignServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-aws-developers': {
      id: '/hire-aws-developers'
      path: '/hire-aws-developers'
      fullPath: '/hire-aws-developers'
      preLoaderRoute: typeof HireAwsDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-flutter-app-developers': {
      id: '/hire-flutter-app-developers'
      path: '/hire-flutter-app-developers'
      fullPath: '/hire-flutter-app-developers'
      preLoaderRoute: typeof HireFlutterAppDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-javascript-developers': {
      id: '/hire-javascript-developers'
      path: '/hire-javascript-developers'
      fullPath: '/hire-javascript-developers'
      preLoaderRoute: typeof HireJavascriptDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-laravel-developers': {
      id: '/hire-laravel-developers'
      path: '/hire-laravel-developers'
      fullPath: '/hire-laravel-developers'
      preLoaderRoute: typeof HireLaravelDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-magento-developers': {
      id: '/hire-magento-developers'
      path: '/hire-magento-developers'
      fullPath: '/hire-magento-developers'
      preLoaderRoute: typeof HireMagentoDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-php-developers': {
      id: '/hire-php-developers'
      path: '/hire-php-developers'
      fullPath: '/hire-php-developers'
      preLoaderRoute: typeof HirePhpDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-python-developers': {
      id: '/hire-python-developers'
      path: '/hire-python-developers'
      fullPath: '/hire-python-developers'
      preLoaderRoute: typeof HirePythonDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-react-native-app-developer': {
      id: '/hire-react-native-app-developer'
      path: '/hire-react-native-app-developer'
      fullPath: '/hire-react-native-app-developer'
      preLoaderRoute: typeof HireReactNativeAppDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-reactjs-developers': {
      id: '/hire-reactjs-developers'
      path: '/hire-reactjs-developers'
      fullPath: '/hire-reactjs-developers'
      preLoaderRoute: typeof HireReactjsDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-shopify-developers': {
      id: '/hire-shopify-developers'
      path: '/hire-shopify-developers'
      fullPath: '/hire-shopify-developers'
      preLoaderRoute: typeof HireShopifyDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-wix-developers': {
      id: '/hire-wix-developers'
      path: '/hire-wix-developers'
      fullPath: '/hire-wix-developers'
      preLoaderRoute: typeof HireWixDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-wordpress-developers': {
      id: '/hire-wordpress-developers'
      path: '/hire-wordpress-developers'
      fullPath: '/hire-wordpress-developers'
      preLoaderRoute: typeof HireWordpressDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-management-software': {
      id: '/hospital-management-software'
      path: '/hospital-management-software'
      fullPath: '/hospital-management-software'
      preLoaderRoute: typeof HospitalManagementSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrm-software': {
      id: '/hrm-software'
      path: '/hrm-software'
      fullPath: '/hrm-software'
      preLoaderRoute: typeof HrmSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-editing': {
      id: '/image-editing'
      path: '/image-editing'
      fullPath: '/image-editing'
      preLoaderRoute: typeof ImageEditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios-app-development-company': {
      id: '/ios-app-development-company'
      path: '/ios-app-development-company'
      fullPath: '/ios-app-development-company'
      preLoaderRoute: typeof IosAppDevelopmentCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page-design': {
      id: '/landing-page-design'
      path: '/landing-page-design'
      fullPath: '/landing-page-design'
      preLoaderRoute: typeof LandingPageDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-seo-services': {
      id: '/local-seo-services'
      path: '/local-seo-services'
      fullPath: '/local-seo-services'
      preLoaderRoute: typeof LocalSeoServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-design-company': {
      id: '/logo-design-company'
      path: '/logo-design-company'
      fullPath: '/logo-design-company'
      preLoaderRoute: typeof LogoDesignCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app-development-services': {
      id: '/mobile-app-development-services'
      path: '/mobile-app-development-services'
      fullPath: '/mobile-app-development-services'
      preLoaderRoute: typeof MobileAppDevelopmentServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-reputation-management-company': {
      id: '/online-reputation-management-company'
      path: '/online-reputation-management-company'
      fullPath: '/online-reputation-management-company'
      preLoaderRoute: typeof OnlineReputationManagementCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-terms-conditions': {
      id: '/our-terms-conditions'
      path: '/our-terms-conditions'
      fullPath: '/our-terms-conditions'
      preLoaderRoute: typeof OurTermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-software': {
      id: '/payroll-software'
      path: '/payroll-software'
      fullPath: '/payroll-software'
      preLoaderRoute: typeof PayrollSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppc-services-company-india': {
      id: '/ppc-services-company-india'
      path: '/ppc-services-company-india'
      fullPath: '/ppc-services-company-india'
      preLoaderRoute: typeof PpcServicesCompanyIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-erp-software': {
      id: '/school-erp-software'
      path: '/school-erp-software'
      fullPath: '/school-erp-software'
      preLoaderRoute: typeof SchoolErpSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-company-in-delhi': {
      id: '/seo-company-in-delhi'
      path: '/seo-company-in-delhi'
      fullPath: '/seo-company-in-delhi'
      preLoaderRoute: typeof SeoCompanyInDelhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-company-india': {
      id: '/seo-company-india'
      path: '/seo-company-india'
      fullPath: '/seo-company-india'
      preLoaderRoute: typeof SeoCompanyIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-outsourcing-services': {
      id: '/seo-outsourcing-services'
      path: '/seo-outsourcing-services'
      fullPath: '/seo-outsourcing-services'
      preLoaderRoute: typeof SeoOutsourcingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services-india': {
      id: '/seo-services-india'
      path: '/seo-services-india'
      fullPath: '/seo-services-india'
      preLoaderRoute: typeof SeoServicesIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smo-company-in-india': {
      id: '/smo-company-in-india'
      path: '/smo-company-in-india'
      fullPath: '/smo-company-in-india'
      preLoaderRoute: typeof SmoCompanyInIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-ux-website-design-company': {
      id: '/ui-ux-website-design-company'
      path: '/ui-ux-website-design-company'
      fullPath: '/ui-ux-website-design-company'
      preLoaderRoute: typeof UiUxWebsiteDesignCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-development': {
      id: '/web-development'
      path: '/web-development'
      fullPath: '/web-development'
      preLoaderRoute: typeof WebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-design-company-india': {
      id: '/website-design-company-india'
      path: '/website-design-company-india'
      fullPath: '/website-design-company-india'
      preLoaderRoute: typeof WebsiteDesignCompanyIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-redesign-company': {
      id: '/website-redesign-company'
      path: '/website-redesign-company'
      fullPath: '/website-redesign-company'
      preLoaderRoute: typeof WebsiteRedesignCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/windows-app-development-services': {
      id: '/windows-app-development-services'
      path: '/windows-app-development-services'
      fullPath: '/windows-app-development-services'
      preLoaderRoute: typeof WindowsAppDevelopmentServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AiSeoServicesRoute: AiSeoServicesRoute,
  AndroidAppDevelopmentServicesRoute: AndroidAppDevelopmentServicesRoute,
  BannerDesignServicesRoute: BannerDesignServicesRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  ContentWritingServicesRoute: ContentWritingServicesRoute,
  CustomCmsWebsiteDesignDevelopmentRoute:
    CustomCmsWebsiteDesignDevelopmentRoute,
  EcommerceSeoServicesRoute: EcommerceSeoServicesRoute,
  EcommerceWebsiteDevelopementRoute: EcommerceWebsiteDevelopementRoute,
  GraphicDesignServicesRoute: GraphicDesignServicesRoute,
  HireAwsDevelopersRoute: HireAwsDevelopersRoute,
  HireFlutterAppDevelopersRoute: HireFlutterAppDevelopersRoute,
  HireJavascriptDevelopersRoute: HireJavascriptDevelopersRoute,
  HireLaravelDevelopersRoute: HireLaravelDevelopersRoute,
  HireMagentoDevelopersRoute: HireMagentoDevelopersRoute,
  HirePhpDevelopersRoute: HirePhpDevelopersRoute,
  HirePythonDevelopersRoute: HirePythonDevelopersRoute,
  HireReactNativeAppDeveloperRoute: HireReactNativeAppDeveloperRoute,
  HireReactjsDevelopersRoute: HireReactjsDevelopersRoute,
  HireShopifyDevelopersRoute: HireShopifyDevelopersRoute,
  HireWixDevelopersRoute: HireWixDevelopersRoute,
  HireWordpressDevelopersRoute: HireWordpressDevelopersRoute,
  HospitalManagementSoftwareRoute: HospitalManagementSoftwareRoute,
  HrmSoftwareRoute: HrmSoftwareRoute,
  ImageEditingRoute: ImageEditingRoute,
  IosAppDevelopmentCompanyRoute: IosAppDevelopmentCompanyRoute,
  LandingPageDesignRoute: LandingPageDesignRoute,
  LocalSeoServicesRoute: LocalSeoServicesRoute,
  LogoDesignCompanyRoute: LogoDesignCompanyRoute,
  MobileAppDevelopmentServicesRoute: MobileAppDevelopmentServicesRoute,
  OnlineReputationManagementCompanyRoute:
    OnlineReputationManagementCompanyRoute,
  OurTermsConditionsRoute: OurTermsConditionsRoute,
  OurWorkRoute: OurWorkRoute,
  PayrollSoftwareRoute: PayrollSoftwareRoute,
  PpcServicesCompanyIndiaRoute: PpcServicesCompanyIndiaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SchoolErpSoftwareRoute: SchoolErpSoftwareRoute,
  SeoCompanyInDelhiRoute: SeoCompanyInDelhiRoute,
  SeoCompanyIndiaRoute: SeoCompanyIndiaRoute,
  SeoOutsourcingServicesRoute: SeoOutsourcingServicesRoute,
  SeoServicesIndiaRoute: SeoServicesIndiaRoute,
  SmoCompanyInIndiaRoute: SmoCompanyInIndiaRoute,
  TestimonialsRoute: TestimonialsRoute,
  UiUxWebsiteDesignCompanyRoute: UiUxWebsiteDesignCompanyRoute,
  WebDevelopmentRoute: WebDevelopmentRoute,
  WebsiteDesignCompanyIndiaRoute: WebsiteDesignCompanyIndiaRoute,
  WebsiteRedesignCompanyRoute: WebsiteRedesignCompanyRoute,
  WindowsAppDevelopmentServicesRoute: WindowsAppDevelopmentServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
